# Ian Braudaway
# CS426-001
# Makefile for Assignment 5 Virtual Memory Manager

all: fifo lru

fifo: vmmfifo.c
	gcc -Wall -Wextra -std=c99 -g vmmfifo.c -o fifo

lru: vmmlru.c
	gcc -Wall -Wextra -std=c99 -g vmmlru.c -o lru
